// import { Asar, Inter } from "next/font/google";
// import "./globals.css";
// import { routing } from "@/src/i18n/routing";
// import enMessages from "../../../messages/en.json";
// import arMessages from "../../../messages/ar.json";
// import Providers from "./providers";

// const inter = Inter({
//   variable: "--font-inter",
//   subsets: ["latin"],
//   weight: ["100", "200", "300", "400", "500", "600", "700"],
// });

// const asar = Asar({
//   variable: "--font-asar",
//   subsets: ["latin"],
//   weight: ["400"],
// });

// export const metadata = {
//   title: {
//     absolute: "",
//     default: "Landing Page",
//     template: "%s | Landing Page",
//   },
//   description: "Generated by create next app",
//   icons: {
//     icon: "/images/.svg",
//   },
// };

// export default function RootLayout({ children, params }) {
//   const locale = params?.locale || "en";
//   const resolvedLocale = routing.locales.includes(locale) ? locale : "en";

//   const messages =
//     { en: enMessages, ar: arMessages }[resolvedLocale] || enMessages;

//   return (
//     <html lang={resolvedLocale} dir={resolvedLocale === "ar" ? "rtl" : "ltr"}>
//       <body
//         className={`${inter.variable} ${asar.variable} bg-colorsBackgroundPrimaryBackground scroll-smooth font-inter`}
//       >
//         <Providers locale={resolvedLocale} messages={messages}>
//           {children}
//         </Providers>
//       </body>
//     </html>
//   );
// }


import { Asar, Inter, Roboto } from "next/font/google";
import "./globals.css";
import { routing } from "@/src/i18n/routing";
import { ThemeProvider } from "@/src/context/ThemeProvider";
import { LanguageProvider } from "@/src/context/LanguageProvider";
import IntlProvider from "@/src/context/IntlProvider";
import enMessages from "../../../messages/en.json";
import arMessages from "../../../messages/ar.json";
import ReactQueryProvider from "../QueryProvider";


// Fonts
const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700"],
});

const asar = Asar({
  variable: "--font-asar",
  subsets: ["latin"],
  weight: ["400"],
});

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
});

// Viewport for responsive SEO
export const viewport = {
  width: "device-width",
  initialScale: 1,
};

export async function generateMetadata({ params }) {
  const locale = params?.locale || "en";
  const isArabic = locale === "ar";

  const title = isArabic ? "FRAKTO PROPTECH" : "FRAKTO PROPTECH";
  const description = isArabic
    ? "شركة Frakto هي منصة تكنولوجيا عقارية (PropTech) تغيّّر طريقة الاستثمار في العقارات. نوصل المستثمرين بفرص حقيقية ومضمونة العائد من خلال شراء، وتطوير، وتأجير العقارات المميزة. نقدّم تجربة استثمارية سريعة، شفافة، ومبنية على بيانات دقيقة وإدارة محترفة."
    : "Frakto is a PropTech platform changing the way you invest in real estate. We connect investors with real, high-yield opportunities through the acquisition, development, and leasing of premium properties. We offer a fast, transparent investment experience built on accurate data and professional management.";

  const keywords = isArabic
    ? [
      "Frakto",
      "استثمار",
      "استثمار آمن",
      "إدارة أموال",
      "استثمار ذكي",
      "تمويل",
    ]
    : [
      "Frakto",
      "investment",
      "financial services",
      "smart investing",
      "secure investments",
      "wealth management",
    ];

  const canonicalUrl = isArabic
    ? "https://frakto.app/ar"
    : "https://frakto.app/en";

  const schemaOrg = {
    "@context": "https://schema.org",
    "@type": "Organization",
    name: isArabic ? "Frakto" : "Frakto",
    url: "https://frakto.app",
    logo: "https://frakto.app/images/Logo.png",
    sameAs: [
      "https://twitter.com/frakto",
      "https://linkedin.com/company/frakto",
    ],
  };

  return {
    title,
    description,
    keywords,
    icons: {
      icon: "/images/Logo.png",
      shortcut: "/images/Logo.png",
      apple: "/images/Logo.png",
    },
    alternates: {
      canonical: canonicalUrl,
      languages: {
        en: "https://frakto.app/en",
        ar: "https://frakto.app/ar",
      },
    },
    openGraph: {
      siteName: "FRAKTO PROPTECH",
      type: "website",
      url: canonicalUrl,
      locale: isArabic ? "ar_SA" : "en_US",
      alternateLocale: isArabic ? ["en_US"] : ["ar_SA"],
      title,
      description,
      images: [
        {
          url: "https://frakto.app/og-image.png",
          width: 1200,
          height: 630,
          alt: isArabic
            ? "FRAKTO - حلول استثمارية آمنة"
            : "FRAKTO - Secure Investment Solutions",
        },
      ],
    },
    twitter: {
      card: "summary_large_image",
      site: "@frakto",
      title,
      description,
      images: ["https://frakto.app/og-image.png"],
    },
    other: {
      "content-language": isArabic ? "ar" : "en",
      "application/ld+json": JSON.stringify(schemaOrg),
    },
  };
}

export default async function RootLayout({ children, params }) {
  const { locale } = await params;
  const resolvedLocale = routing.locales.includes(locale) ? locale : "en";

  const messages =
    { en: enMessages, ar: arMessages }[resolvedLocale] || enMessages;

  return (
    <html
      lang={resolvedLocale}
      dir={resolvedLocale === "ar" ? "rtl" : "ltr"}
    >
      <body
        className={`${inter.variable} ${asar.variable} ${roboto.variable} bg-colorsBackgroundPrimaryBackground scroll-smooth font-roboto`}
      >
        <ThemeProvider>
          <ReactQueryProvider>
            <LanguageProvider>
              <IntlProvider locale={resolvedLocale} messages={messages}>
                {children}
              </IntlProvider>
            </LanguageProvider>
          </ReactQueryProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}